export type Config = Record<string, string>;

export const DEFAULT_CONFIG: Config = {
  PORT: "3000",
  JIRA_BASE_URL: "",
  JIRA_USER_EMAIL: "",
  JIRA_API_TOKEN: "",
  JIRA_WEBHOOK_SECRET: "",
  READY_STATUS: "To Do",
  IN_PROGRESS_STATUS: "In Progress",
  IN_REVIEW_STATUS: "In Review",
  GITHUB_TOKEN: "",
  GH_TOKEN: "",
  REQUIRE_GITHUB_AUTH: "true",
  AI_AGENT: "codex",
  CODEX_API_KEY: "",
  OPENAI_API_KEY: "",
  CODEX_BOOTSTRAP_LOGIN: "true",
  CODEX_DEVICE_LOGIN_ON_START: "true",
  CLAUDE_BOOTSTRAP_LOGIN: "true",
  CLAUDE_DEVICE_LOGIN_ON_START: "true",
  WORKFLOW_BASE_BRANCH: "main",
  CODEX_EXEC_ARGS: "--full-auto --sandbox danger-full-access",
  ANTHROPIC_API_KEY: "",
  CLAUDE_EXEC_ARGS: "--allowedTools Bash,Edit,Write,Read",
  NGROK_ENABLE: "false",
  NGROK_AUTHTOKEN: "",
  NGROK_API_KEY: "",
  NGROK_DOMAIN: ""
};
